### ISSUE TITLE
Wheel for Linux 64 bits

### ISSUE THREAD

**Issue by borgeser** [bluesheeptoken/CPT#104]
Hello, 

I hope this one will be easier than Mac OS. I'd like to have a wheel for Linux 64bits.

The suffix for the architecture is `aarch64`, here is an example of the naming : `pandas-1.5.1-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl`.

Thanks a lot.

**Comment by borgeser** [comment]
It's strange.

(I'm on Docker on my Mac M1). If I do `pip install cpt`, since the wheel is missing, pip is trying to build from sources and fails.
However, if I clone this project and run `pip wheel .`, the wheel is created without problem and I can use it later.

**Comment by bluesheeptoken** [comment]
Hey Roland,
Thanks for bringing this up.

If my memory serves me right, I don't publish wheels for arch architecture. And I think the ongoing PR might fix this (if you can try with the command I sent you for macos, I would be glad. I am struggling to find it with github mobile :D)

If that does not work, can you provide me the base image you are using ? I think it will be easier to reproduce than the macos one !

I will have a look next week once I come back from m'y hollidays :)

**Comment by borgeser** [comment]
Yes I think too the 

```
[build-system]
requires ...
```

part is the culprit of the failure.

Have nice holidays, we'll see that next week ;)

**Comment by bluesheeptoken** [comment]
Indeed, github does not have arm workers :(
I will soon reenable Travis CI (as numpy) because it supports ARM. I will let you know once it's done

**Comment by bluesheeptoken** [comment]
I am requesting travis CI some free credits to publish the wheels.
I will publish wheels on pypitest as soon as I get them (if I get them). On which Python version are you running? So I can publish only this version for now.

**Comment by borgeser** [comment]
Thanks a lot for your dedication :)
I'm using python 3.8 on my project.

**Comment by bluesheeptoken** [comment]
:)
Here we go, project published for 3.8: `pip install -i https://test.pypi.org/simple/ cpt==1.3.3.dev1` can you tell me if this working fine for you?

**Comment by borgeser** [comment]
> :) Here we go, project published for 3.8: `pip install -i https://test.pypi.org/simple/ cpt==1.3.3.dev1` can you tell me if this working fine for you?

It's working!

**Comment by bluesheeptoken** [comment]
Perfect, I will release that this week for all the versions :)
Thanks for thé feedback

**Comment by bluesheeptoken** [comment]
This is now completely released. Version 1.3.3 contains wheels for arm architecture 🥳
