### ISSUE TITLE
cpt.alphabet

### ISSUE THREAD

**Issue by catchthemonster** [bluesheeptoken/CPT#106]
Hi Louis,
I successfully installed cpt package under py-3.12.1
on the import however i get:
./python3.12
Python 3.12.1 (main, Dec 25 2023, 10:27:39) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from cpt.cpt import Cpt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "cpt/cpt.pyx", line 1, in init cpt
ModuleNotFoundError: No module named 'cpt.alphabet'; 'cpt' is not a package

could I help with this?

**Comment by catchthemonster** [comment]
I tested with py-3.11.0 and it works!
Why is not working with 3.12.1 is not clear to me

**Comment by bluesheeptoken** [comment]
Hello Sasha !
It looks like I am late for the Python 3.12 release :) I will try to release it soon

but if you wish to help me releasing it, you can get inspiration from the Python 3.11 release commits

**Comment by catchthemonster** [comment]
Hi Louis! I will crank myapp via 3.11.0 for now to keep coding my app...
As far as 3.12.x yes I will help you, just please point me to some documentation or steps how to try to build cpt on 3.12 and I will help you.

As always thanks for everything ...

**Comment by bluesheeptoken** [comment]
I don't know why I did several commits for that...
But here they are: [Windows support](https://github.com/bluesheeptoken/CPT/commit/28be0dcc04de7bd27125a550063c12daf8a5bbd3), the [linux aarch64 support](https://github.com/bluesheeptoken/CPT/blob/master/.travis.yml#L61-L72), and [the github actions for linux / macos intel](https://github.com/bluesheeptoken/CPT/blob/master/.github/workflows/publish-pypi.yml).
For the two last links, I think duplicating the config and replacing 311 by 312 should do the trick.

If I find time to do it before you do, I will ping you on the PR to save you time

After that I will publish a 1.3.4 version myself !

Thanks for opening the issues

**Comment by catchthemonster** [comment]
Cool I will check tomorrow and forward when I get some time. Work comes
first...

**Comment by bluesheeptoken** [comment]
#107 Publishes for python 3.12 !

**Comment by catchthemonster** [comment]
Awesome, thanks for the update!

**Comment by bluesheeptoken** [comment]
Thanks for bringing this to my attention. I didnt follow the newest python versions recently :x
