### ISSUE TITLE
CPT cannot predict an element already present in this sequence (Cf how to tune the "CPT model"): What does it mean

### ISSUE THREAD

**Issue by rt3722** [bluesheeptoken/CPT#67]

**Comment by rt3722** [comment]
What does this mean

**Comment by bluesheeptoken** [comment]
Thanks for your interest for CPT !

Given a sequence, and call it like `model.predict([[0, 1, 1, 1, 1, 2]])`, the model prediction won't be `0`, `1` or `2`. That is why CPT needs a good tuning. (You can use the gridsearch module from sklearn for that)

This can be explained with the way of predicting of CPT. Taken from the original research paper,

>  The consequent of a sequence Y with
respect to a sequence S is the subsequence of Y starting after the last item in
common with S until the end of Y . Each item of each of those consequents
are then stored in a structure named Count Table (CT). A CT is defined as a
hash table with items as keys and a score as associated value. This structure
holds a list of possible candidate items and their respective score for a specific
prediction and hence is unique for each individual prediction task. The item
with the highest score within the CT is the predicted item

Note the "taken after the last item in common with S", which means you the prediction won't be an element in the sequence.


If you feel like this sentance can be reword, feel free to tell me or do a PR, I am having a headache to find the right sentance to explain this problem.


Do the explanations answer your question?

**Comment by rt3722** [comment]
Thank you. I got your point

**Comment by bluesheeptoken** [comment]
If you need any help / have any questions, do not hesitate !
