### ISSUE TITLE
pls example that your code is better than neural networks based code ?

### ISSUE THREAD

**Issue by Sandy4321** [bluesheeptoken/CPT#91]
great code
but do you have example that your code is better than neural networks based code ?

**Comment by bluesheeptoken** [comment]
Hello @Sandy4321 

Thanks for starring the project and your interest in it.
Unfortunately, I don't have such code to "prove" which one is better. I guess it depends the dataset and the tuning.

If you have a working NN architecture you want to compare CPT with, I would be glad to help you. I don't think this should be too hard to implement the comparison once you have a NN architecture

**Comment by catchthemonster** [comment]
Hi Sandy4321,
create a nn example and pass it here and I will run my implementation of cpt (thanks to author) and give you stats.
For what is worth, cpt for me works really well and it is fast, and utilizing all my cores to the max ...
Regards

**Comment by Sandy4321** [comment]
sorry I do not have  nn implementation
just wanted to know about one of alternatives

we may understand performance improving only by comparison

by the way what baseline you use ?

**Comment by bluesheeptoken** [comment]
Unfortunately, the authors have not benchmarked against custom RNN architecture. (the benchmarks of accuracy can be found here: http://www.philippe-fournier-viger.com/spmf/PAKDD2015_Compact_Prediction_tree+.pdf)
