### ISSUE TITLE
py -3.10.3 cpt build error ...

### ISSUE THREAD

**Issue by catchthemonster** [bluesheeptoken/CPT#92]
Hi Louis,
Trying to compile cpt via pip on py 3.10.3 and getting errors:

Collecting cpt
  Using cached cpt-1.3.0.tar.gz (113 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'

  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1568 lines of output]
      Compiling cpt/alphabet.pyx because it depends on /cube/api/py-3.10.3/lib/python3.10/site-packages/Cython/Includes/cpython/type.pxd.
      Compiling cpt/cpt.pyx because it depends on /cube/api/py-3.10.3/lib/python3.10/site-packages/Cython/Includes/cpython/type.pxd.
      [1/2] Cythonizing cpt/alphabet.pyx
      [2/2] Cythonizing cpt/cpt.pyx
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      from cpt.prediction_tree cimport PredictionTree
      ^
      ------------------------------------------------------------
      
      cpt/cpt.pxd:1:0: 'cpt/prediction_tree.pxd' not found
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      from cpt.prediction_tree cimport PredictionTree
      ^
      ------------------------------------------------------------
      
      cpt/cpt.pxd:1:0: 'cpt/prediction_tree/PredictionTree.pxd' not found
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      from cpt.prediction_tree cimport PredictionTree
      from cpt.alphabet cimport Alphabet
      ^
      ------------------------------------------------------------
      
      cpt/cpt.pxd:2:0: 'cpt/alphabet.pxd' not found
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      from cpt.prediction_tree cimport PredictionTree
      from cpt.alphabet cimport Alphabet
      ^
      ------------------------------------------------------------
      
      cpt/cpt.pxd:2:0: 'cpt/alphabet/Alphabet.pxd' not found
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      from cpt.prediction_tree cimport PredictionTree
      from cpt.alphabet cimport Alphabet
      from cpt.bitset cimport Bitset
      ^
      ------------------------------------------------------------
      
      cpt/cpt.pxd:3:0: 'cpt/bitset.pxd' not found
      
      Error compiling Cython file:
      -----------------------------------------------------------

did you try to compile cpt against 3.10.3

regards,

**Comment by bluesheeptoken** [comment]
Oups, sorry for that. I didn't follow the releases, and I had not in mind python 3.10 was out.

I will update the CIs to publish for 3.10!

**Comment by bluesheeptoken** [comment]
I kinda messed up the publish process ^^', but basically in a few steps, it should look something like this: #93
Can you confirm it works for you?

As you suggested, do not hesitate to do it if you think it's relevant for python 3.11

Thanks for being active on the repo! And do not hesitate to @ me, I don't always see the issues, unfortunately.

**Comment by catchthemonster** [comment]
Sounds good!
I will do this tomorrow and let you know.
Thanks for doing this ...
--sasha

**Comment by catchthemonster** [comment]
Luis, next time I stop by Paris to see my ant, I will ping you and take you
for coffee...
Best

**Comment by bluesheeptoken** [comment]
I am glad it worked !

Do not hesitate to ping me again.

> Luis, next time I stop by Paris to see my ant, I will ping you and take you for coffee...

I know some pretty cool beer places too :D
